Site/mafia/mafia/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from mainpage.views import pageNotFound

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('accounts/', include('registration.urls')),
    path('profile/', include('user_profile.urls')),
    path('lobby/', include('lobbypage.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = pageNotFound

Site/mafia/user_profile/urls.py
from django.urls import path, include

from .views import *

urlpatterns = [
    path('', profile, name="profile"),
    path('settings/', settings_profile, name="settings_profile"),
    path('edit/', edit_profile, name="edit_profile"),
    path('friends-search/', friends_search, name="friends_search"),
    path('friends/', friends_list, name="friends"),
    path('notice/', notice, name="notice"),
    path('notice/delete_record/<int:record_id>/', delete_notice, name='delete_record'),
    path('notice/new_notices_check_view/', new_notices_check_view, name='new_notices_check_view'),
    path('<slug>/', show_profile, name="show_profile"),
    path('<slug>/add_friendship_record/', add_friendship_notice, name="add_friendship_record"),
    path('<slug>/delete_friendship_record/', delete_friendship_notice, name="delete_friendship_record"),
    path('ajax/add_record/', add_notice, name='add_record'),
]

Site/mafia/user_profile/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from pytils.translit import slugify
from lobbypage.models import Rooms
from django.utils.translation import gettext_lazy as _


class Profile(models.Model):
    profile_img = models.ImageField(upload_to='profileImg/', default='profileImg/AnonIcon.jpg', blank=False,
                                    verbose_name='Фото профиля')
    nickname = models.CharField(max_length=20, blank=False, verbose_name='Никнейм')
    slug = models.SlugField(max_length=50, blank=True, unique=True, db_index=True, verbose_name='URL')
    micro_value_lvl = models.IntegerField(validators=[MaxValueValidator(100), MinValueValidator(0)], default=50,
                                          verbose_name='Громкость микрофона')
    micro_index = models.IntegerField(validators=[MinValueValidator(-1)], default=0, verbose_name='Выбранный микрофон')
    webcam_index = models.IntegerField(validators=[MinValueValidator(-1)], default=0, verbose_name='Выбранная камера')
    related_user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Аккаунт профиля')
    related_lobby = models.ForeignKey(Rooms, on_delete=models.SET_NULL, null=True, blank=True,
                                      verbose_name='Связанное лобби')

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

    def __str__(self):
        return self.nickname + ' @' + self.related_user.username

    def get_absolute_url(self):
        return reverse('show_profile', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(str(self.nickname) + '-id' + str(self.related_user.pk))
        super(Profile, self).save(*args, **kwargs)


class GameHistory(models.Model):
    roomname = models.CharField(blank=False, max_length=40)
    data = models.DateField()
    win = models.IntegerField(default=-1)
    playerlist = models.JSONField(null=True, default=dict)
    players = models.ManyToManyField(Profile)

    def get_datetime(self):
        return self.data.strftime('%d.%m.%y')



class Notice(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Отправитель')
    addressee = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False, verbose_name='Адресат')
    datetime = models.DateTimeField(auto_now_add=True)
    invite_lobby = models.ForeignKey(Rooms, on_delete=models.CASCADE, blank=True, null=True,
                                     verbose_name='Лобби из приглашения')

    class NoticeType(models.TextChoices):
        FRIENDSHIP = "FR", _("Friendship")
        INVITE = "IV", _("Invite")
        INFO = "IF", _("Info")

    notice_type = models.CharField(max_length=2, choices=NoticeType.choices, default=NoticeType.INFO,
                                   verbose_name='Тип уведомления', blank=False)

    text_message = models.CharField(max_length=100, verbose_name='Сообщение', blank=True)

    class Meta:
        verbose_name = "Уведомление"
        verbose_name_plural = "Уведомления"

    def get_datetime(self):
        return self.datetime.strftime('%d.%m %H:%M')

    def __str__(self):
        str_type = ''
        if self.notice_type == self.NoticeType.INFO:
            str_type = 'INFO для ' + self.addressee.nickname
        elif self.notice_type == self.NoticeType.FRIENDSHIP:
            str_type = 'FRIENDSHIP для ' + self.addressee.nickname
        elif self.notice_type == self.NoticeType.INVITE:
            str_type = 'INVITE для ' + self.addressee.nickname
        return str_type

    def save(self, *args, **kwargs):
        if (len(str(self.text_message)) - str(self.text_message).count(" ") == 0
            and self.notice_type == self.NoticeType.INFO) \
                or (self.sender == None and self.notice_type != self.NoticeType.INFO) \
                or (self.sender != None and self.sender.profile == self.addressee):
            return

        if self.notice_type == self.NoticeType.INFO:
            self.text_message = str(self.text_message).capitalize()
        elif self.notice_type == self.NoticeType.FRIENDSHIP:
            self.text_message = str(self.sender.profile.nickname) + ' хочет добавить вас в друзья!'
        elif self.notice_type == self.NoticeType.INVITE:
            self.text_message = str(self.sender.profile.nickname) + ' приглашает вас в игру!'

        super(Notice, self).save(*args, **kwargs)


class Friend(models.Model):
    related_user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Аккаунт профиля')
    friends = models.ManyToManyField(Profile)

    def __str__(self):
        return 'Друзья ' + self.related_user.profile.nickname

    def save(self, *args, **kwargs):
        super(Friend, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Друзья"
        verbose_name_plural = "Друзья"

Site/mafia/user_profile/forms.py
from django import forms
from .models import Profile
from django import forms


class EditProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    nickname = forms.CharField(label="Новый никнейм", max_length=20)
    profile_img = forms.ImageField(label="Новое фото профиля:", required=False)

    class Meta:
        model = Profile
        fields = ('profile_img', 'nickname')


class FriendsSearchForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    nickname = forms.CharField(label="Никнейм пользователя:", max_length=20)

    class Meta:
        model = Profile
        fields = ('nickname',)

Site/mafia/user_profile/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from .models import *
from .forms import EditProfileForm, FriendsSearchForm


def profile(request):
    if request.user.is_authenticated:
        return redirect(show_profile, request.user.profile.slug)
    else:
        return redirect('login')


def show_profile(request, slug):
    showed_profile = get_object_or_404(Profile, slug=slug)
    data = {'user_profile': showed_profile}

    if request.user.is_authenticated and showed_profile == request.user.profile:
        data['login'] = request.user.username
        data['edit'] = True
        return render(request, 'profile/profile.html', data)
    else:
        data['login'] = ''
        data['edit'] = False
        friendship = request.user.friend.friends.all().filter(pk=showed_profile.pk).exists()
        if friendship:
            data['friend'] = True
        else:
            if request.user.profile.notice_set.all().filter(sender=showed_profile.related_user).filter(
                    notice_type=Notice.NoticeType.FRIENDSHIP).exists():
                data['friendship_notice_get'] = request.user.profile.notice_set.all().get(sender=showed_profile.related_user, notice_type=Notice.NoticeType.FRIENDSHIP).pk
            elif showed_profile.notice_set.all().filter(sender=request.user).filter(
                    notice_type=Notice.NoticeType.FRIENDSHIP).exists():
                data['friendship_notice_send'] = True
            else:
                data['not_friend'] = True

    return render(request, 'profile/show_profile.html', data)


# def edit_profile(request):
#     if request.user.is_authenticated:
#
#         data = {'error': "Ошибка редактирования профиля! Проверьте правильность заполнения полей формы!"}
#         if request.method == 'GET':
#
#             render(request, 'html успешного редактирования')
#
#         form = EditProfileForm()
#         form.nickname = request.user.profile.nickname
#         form.profile_img = request.user.profile.profile_img
#
#         if request.method == 'POST':
#             var = form
#             form = EditProfileForm(request.POST, request.FILES)
#             if not form.is_valid():
#                 data['form'] = var
#                 return render(request, 'html профиля', data)
#
#         data['form'] = form
#         form_obj = form.instance
#         data['form'] = form
#         data['form_obj'] = form_obj
#         form.save(commit=False)
#         return render(request, 'html профиля', data)
#
#     else:
#         return render_to_string('<h1>ЭЭЭЭЭ, залогинся!</h1>')


def edit_profile(request):
    if request.user.is_authenticated:
        data = {}
        get_profile = Profile.objects.get(related_user=request.user)

        if request.method == 'POST':
            form = EditProfileForm(request.POST, request.FILES, instance=get_profile)
            if form.is_valid():
                form.save()
                return redirect(get_profile)

        form = EditProfileForm(instance=get_profile)
        data['form'] = form
        data['form_obj'] = get_profile
        return render(request, 'edit_profile.html', data)

    else:
        return redirect('login')


def settings_profile(request):
    if request.user.is_authenticated:
        return render(request, 'profile/profile_settings.html', {'request': request})
    else:
        return redirect('login')


def friends_search(request):
    data = {}
    if request.user.is_authenticated:
        data['user_profile'] = request.user.profile
        data['form'] = FriendsSearchForm(initial={'nickname': 'введите никнейм'})
        if 'nickname' in request.GET:
            data['form'] = FriendsSearchForm(request.GET)
            if data['form'].is_valid():
                search_nickname = data['form'].cleaned_data['nickname']
                search_result = Profile.objects.filter(nickname__icontains=search_nickname)
                if search_result.count() > 0:
                    data['search_result'] = search_result
                else:
                    data['search_result'] = False
                    data['message'] = 'По вашему запросу ничего не найдено'
        else:
            data['message'] = 'Здесь будут перечислены найденные профили'

        return render(request, 'profile/friends_search.html', data)
    else:
        return redirect('login')


def notice(request):
    if request.user.is_authenticated:
        data = {}
        data['notices'] = Notice.objects.filter(addressee=request.user.profile)
        data['empty'] = (data['notices'].count() == 0)
        data['notices'] = reversed(data['notices'])
        return render(request, 'profile/notice.html', data)
    else:
        return redirect('login')


def friends_list(request):
    if request.user.is_authenticated:
        data = {}
        data['friends'] = Friend.objects.get(related_user=request.user).friends.all()
        return render(request, 'profile/friends_list.html', data)
    else:
        return redirect('login')


@csrf_exempt
def delete_notice(request, record_id):
    response = {'notice_id': record_id}
    get_notice = Notice.objects.get(pk=record_id)

    if get_notice.notice_type == Notice.NoticeType.FRIENDSHIP:
        response_notice = Notice()
        response_notice.notice_type = Notice.NoticeType.INFO
        response_notice.text_message = "Ваша заявка в друзья была отклонена!"
        response_notice.addressee = get_notice.sender.profile
        response_notice.sender = get_notice.addressee.related_user
        response_notice.save()

    get_notice.delete()
    response['message'] = 'Запись успешно удалена.'
    return JsonResponse(response)


@csrf_exempt
def add_notice(request):
    response = {'notice_id': request.POST.get("record_id")}
    try:
        get_notice = Notice.objects.get(pk=int(request.POST.get("record_id")))

        user1 = get_notice.sender
        user2 = get_notice.addressee.related_user

        user1.friend.friends.add(user2.profile)
        user2.friend.friends.add(user1.profile)

        response_notice = Notice()
        response_notice.notice_type = Notice.NoticeType.INFO
        response_notice.text_message = "принял вашу заявку в друзья!"
        response_notice.sender = user2
        response_notice.addressee = user1.profile
        response_notice.save()

        get_notice.delete()
        response['message'] = 'Запись успешно удалена.'
    except Exception:
        response['message'] = 'ERROR'

    return JsonResponse(response)


@csrf_exempt
def add_friendship_notice(request, slug):
    sender = request.user
    addressee = Profile.objects.get(slug=slug)

    response_notice = Notice()
    response_notice.notice_type = Notice.NoticeType.FRIENDSHIP
    response_notice.text_message = "Заявка отправлена"
    response_notice.sender = sender
    response_notice.addressee = addressee
    response_notice.save()

    response = {'message': 'Уведомление отправлено'}
    return JsonResponse(response)


@csrf_exempt
def delete_friendship_notice(request, slug):
    profile1 = request.user.profile
    profile2 = Profile.objects.get(slug=slug)

    profile1.related_user.friend.friends.remove(profile2)
    profile2.related_user.friend.friends.remove(profile1)

    response_notice = Notice()
    response_notice.notice_type = Notice.NoticeType.INFO
    response_notice.text_message = "Вас удалил из друзей!"
    response_notice.sender = profile1.related_user
    response_notice.addressee = profile2
    response_notice.save()

    response = {'message': 'Уведомление отправлено'}
    return JsonResponse(response)


@csrf_exempt
def new_notices_check_view(request):
    if request.method == "POST":

        htmlCode = ""
        notices = Notice.objects.filter(addressee=request.user.profile)


        if (notices.count() > 0):
            k = notices.count() - 1
            while k >= 0:
                htmlCode += render_to_string("profile/notices_pack_ajax.html", {'notice': notices[k]})
                k -= 1
        else:
            htmlCode += "<tr id='notnoticerecord' style='text-align: center;'><td style='text-align: center;'>Уведомлений нет</td><td></td></tr>"

        response = {'message': 'Кол-во проверено', "htmlCode": htmlCode}
        return JsonResponse(response)

Site/mafia/user_profile/templates/profile/friends_list.html
{% extends 'profile_base.html' %}
 
{% block title %}Уведомления{% endblock %}
 
{% block content %}
<div id="header">
    <a class="ExitButton" href="{% url 'mainpage'%}">🡸</a><br>
    <h2 id ="head-title">Ваши Друзья</h2>
    <a class="ExitButton" href="{% url 'friends_search'%}">🔎</a>
</div>
<div class="list">
    <table>
    {% if friends %}
		{% for friend in friends %}
            <tr>
                <td>
                    <div style="display: flex;flex-direction: row; justify-content: flex-start;">
                        <img class="profile-Icon" width="45px" height="45px" src="{{friend.profile_img.url}}" alt="Icon">
                        <div style="display: flex; align-items: center;">
                          <a class="links" href="{{ friend.get_absolute_url }}">{{friend.nickname }}</a>
                        </div>
                    </div>                    
                </td>
		    </tr>
        {% endfor %}
    {% else %}
    <tr>
        <div style="display: flex; justify-content: center;">
            У вас нет друзей!
        </div>
    </tr>
    {% endif %}
    </table>
</div>
{% endblock content%}

{% block style %}
<style>
    *{
        margin: 0;
        padding: 0;
    }
    body{
        font-family: sans-serif;
        font-size: 20px;
        min-height: 100vh;
        background: linear-gradient(135deg, rgb(243, 46, 46) 0%, rgb(78, 9, 16) 100%);
    }
    main{
        width: 21em;
        height: 33em;
        display: flex;
        flex-direction: column;
        align-items: center;
        padding-top: 1em;
    }
    #header{
        display: flex;
        justify-content: center;
    }
    #head-title{
        margin: 1em 0 1em 0;
        padding-left: 1.5em;
        white-space: nowrap;
        text-align: center;
    }
    p{
        font-size: 16px;
        margin-left: 1em;
    }

    .list{
    width: 21em;
    height: 30em;
    background-color: #292e36;
    overflow-y: scroll;
    margin-bottom: 1em;
    scrollbar-width: thin;
    scrollbar-color: var(--thumbBG) var(--scrollbarBG);
    padding: 0.5em;
  }

    

  html {
    --scrollbarBG: #27303f;
    --thumbBG: #90A4AE;
  }
  .list::-webkit-scrollbar-corner {
    background: #27303f;
  }
  .list::-webkit-scrollbar {
    width: 11px;
    height: 11px;
  }
  .list::-webkit-scrollbar-track {
    background: var(--scrollbarBG);
  }
  .list::-webkit-scrollbar-thumb {
    background-color: var(--thumbBG) ;
    border-radius: 6px;
    border: 3px solid var(--scrollbarBG);
  }
  table {
    width:100%;
    border-collapse:separate; 
    border-spacing:0 0.2em;
  }
  tr{
    height: 100%;
    background-color: #363d48;
  }
  td{
    height: 100%;
    padding: 0.3em;
    border-radius: 10px;
  }

  tr>td {
    margin-bottom: 30px;
  }
  
  .text-message::first-letter{
    text-transform: lowercase;
  }

  .profile-Icon{
    background: linear-gradient(#fff, #fff) padding-box,
    linear-gradient(45deg, rgb(3, 25, 151), #0b9ef9) border-box;
    border: 3px solid transparent;
    border-radius: 10px;
    margin-right: 0.5em;
    margin-left: 0.5em;
  }
  .links{
    color:rgb(114, 143, 248);
    text-decoration: none;
  }
  .links:hover{
    text-decoration: underline;
  }
</style>
{% endblock%}

Site/mafia/user_profile/templates/profile/friends_search.html
{% extends 'profile_base.html' %}
 
{% block title %}Поиск друзей{% endblock %}
 
{% block content %}
<div id="head">
	<a class="ExitButton" href="{% url 'mainpage'%}">🡸</a>
	<h2>Поиск друзей</h2>
</div>
<div>
	<form method="get">
		<div id="input-nick">
			{{form.nickname}}
			<input type="submit" value="Поиск" >
		</div>
	</form>
	<div class="list">
		<table>
		{% if search_result %}
			{% for profile in search_result %}
				<tr>
					<td>
						<div style="display: flex;flex-direction: row; justify-content: flex-start;">
							<img class="profile-Icon" width="45px" height="45px" src="{{profile.profile_img.url}}" alt="Icon">
							<div style="display: flex; align-items: center;">
							  <a class="links" href="{{ profile.get_absolute_url }}">{{profile.nickname }}</a>
							</div>
						</div>                    
					</td>
				</tr>
			{% endfor %}
		{% else %}
		<p style="display: flex; justify-content: center;">{{ message }}</p>
		{% endif %}
		</table>
	</div>

</div>
{% endblock content%}

{% block style %}
<style>
	#input-nick{
		display: flex;
		flex-direction: row;
		align-items: center;
	}
	input[type="text"]
	{
		margin-top: 0.5em;
		margin-bottom: 0.5em;
		padding: 1%;
		padding-top: 3.5%;
		padding-bottom: 3.5%;
		border-radius: 5px 0 0 5px;
		font-size: 16px;
		width: 100%;
		height: 1.5em;
		border-width: 0;
	}
	input[type="submit"]{
		padding-top: 5px;
		padding-bottom: 5px;
		margin-top: 0;
		margin-left: 0em;
		border-radius: 0 5px 5px 0;
		height: 1.85em;
	}
	p{
        font-size: 16px;
        margin-left: 1em;
    }

    .list{
    width: 21em;
    height: 25em;
    background-color: #292e36;
    overflow-y: scroll;
    margin-bottom: 1em;
    scrollbar-width: thin;
    scrollbar-color: var(--thumbBG) var(--scrollbarBG);
    padding: 0.5em;
  }

    

  html {
    --scrollbarBG: #27303f;
    --thumbBG: #90A4AE;
  }
  .list::-webkit-scrollbar-corner {
    background: #27303f;
  }
  .list::-webkit-scrollbar {
    width: 11px;
    height: 11px;
  }
  .list::-webkit-scrollbar-track {
    background: var(--scrollbarBG);
  }
  .list::-webkit-scrollbar-thumb {
    background-color: var(--thumbBG) ;
    border-radius: 6px;
    border: 3px solid var(--scrollbarBG);
  }
  table {
    width:100%;
    border-collapse:separate; 
    border-spacing:0 0.2em;
  }
  tr{
    height: 100%;
    background-color: #363d48;
  }
  td{
    height: 100%;
    padding: 0.3em;
    border-radius: 10px;
  }

  tr>td {
    margin-bottom: 30px;
  }
  
  .text-message::first-letter{
    text-transform: lowercase;
  }

  .profile-Icon{
    background: linear-gradient(#fff, #fff) padding-box,
    linear-gradient(45deg, rgb(3, 25, 151), #0b9ef9) border-box;
    border: 3px solid transparent;
    border-radius: 10px;
    margin-right: 0.5em;
    margin-left: 0.5em;
  }
  .links{
    color:rgb(114, 143, 248);
    text-decoration: none;
  }
  .links:hover{
    text-decoration: underline;
  }
	
</style>
{% endblock%}

Site/mafia/user_profile/templates/profile/profile.html
{% extends 'profile_base.html' %}
 
{% block title %}Профиль{% endblock %}
{% block script %}{% endblock %}
{% block style %}
<style>
	table {
    	width:100%;
    	border-collapse:separate; 
    	border-spacing:0 0.2em;
	}
	tr{
    	/* height:100%; */
    	background-color: #363d48;
  	}
  	td{
    	/* height: 100%;
    	width: 100%; */
    	padding: 0.3em;
  	}
  	tr>td {
    	margin-bottom: 30px;
  	}
	.list{
   		width: 100%;
    	height: 30em;
    	background-color: #292e36;
    	overflow-y: scroll;
    	margin-bottom: 1em;
		scrollbar-width: thin;
		scrollbar-color: var(--thumbBG) var(--scrollbarBG);
		padding: 0.5em;
  	}
	html {
		--scrollbarBG: #27303f;
		--thumbBG: #90A4AE;
	}
	.list::-webkit-scrollbar-corner {
		background: #27303f;
	}
	.list::-webkit-scrollbar {
		width: 11px;
		height: 11px;
	}
	.list::-webkit-scrollbar-track {
		background: var(--scrollbarBG);
	}
	.list::-webkit-scrollbar-thumb {
		background-color: var(--thumbBG) ;
		border-radius: 6px;
		border: 3px solid var(--scrollbarBG);
	}
</style>
{% endblock %}
{% block content %}
<div id="head">
	<a class="ExitButton" onclick="javascript:history.back(); return false;">🡸</a>
	<h1 style="margin-bottom: 0em; margin-top: 0.5em;">Профиль</h1>
</div>
<div class="content">
	<div id="ProfileCard">
		<div style="width: 200px; height: 200px; display: flex; justify-content: center;align-items:center;	"	>
			<img id="profile-Icon" width="180" height="180" src="{{user_profile.profile_img.url}}" alt="Icon">
		</div>
			{% if edit %}
				<div class="profile_data" >
					<p id ="Nickname">{{user_profile.nickname}}</p>
					<p id ="LogName">@{{login}}</p>
					<a id ="EditProfile" href="{% url "edit_profile" %}">Изменить</a>
				</div>
			{%else%}
				{% if friend %}
				<div class="profile_data" >
					<p id ="Nickname">{{user_profile.nickname}}</p>
					<div style="height: 26px;display: block;margin-top: auto;align-self:flex-end;margin-bottom: 1px;">
					<button id ="EditProfile" class='delete_friendship-button'>Удалить из друзей &#10134;</button>
					</div>
				</div>
				{% endif %}
				{% if friendship_notice_get %}
				<div class="profile_data">
					<p id ="Nickname">{{user_profile.nickname}}</p>
					<div style="height: 26px;display: block;margin-top: auto;align-self:flex-end;">
						<button id ="EditProfile" class='answer_friendship-button' data-record-id="{{ friendship_notice_get }}">Одобрить заявку &#10133;</button>
					</div>
					
				</div>
				{% endif %}
				{% if not_friend %}
				<div class="profile_data">
					<p id ="Nickname">{{user_profile.nickname}}</p>
					<div style="height: 26px;display: block;margin-top: auto;align-self:flex-end;">
						<button id ="EditProfile" class='friendship-button'>Добавить в друзья</button>
					</div>
					
				</div>
				{% endif %}
				{% if friendship_notice_send %}
				<div class="profile_data">
					<!-- style="align-items: center; margin-bottom: auto; margin-top: auto;" -->
					<p id ="Nickname">{{user_profile.nickname}}</p>
					<div style="height: 26px;display: block;margin-top: auto;align-self:flex-end;"></div>
				</div>
				{% endif %}
			{% endif %}
	</div>
</div>
<div style="display: flex; justify-content: center; margin-left: 50px;">
	<h2>История игр</h2>
</div>
<hr>
<div class="content">
	<div id="GamesHistory" class="list">
		<table cellspacing="0" cellpadding="0">
			<tr>
				<td>
					Дата
				</td>
				<td style="padding-left: 1em;">
					Название лобби
				</td>
				<td style="padding-left: 2em;">
					Результат
				</td>
				<td style="padding-left: 1em;">
					Роль
				</td>
			</tr>
			{% for game in user_profile.gamehistory_set.all%}
				<tr>
					<td>
						{{game.get_datetime}}
					</td>
					<td style="padding-left:1em;">
						{{game.roomname}}
					</td>
					<td style="padding-left:2em;">
						{% if game.win == 1 %}
							Мирные
						{% else %}
							Мафия
						{% endif %}
					</td>
					<td style ="padding-left: 1em;">
						{% for key, value in game.playerlist.items %}
							{% if key == user_profile.pk|slugify %}
								{% if value == 'civil' %}
									Гражданин
								{% endif %}
								{% if value == 'com' %}
									Комиссар
								{% endif %}
								{% if value == 'doc' %}
									Доктор
								{% endif %}
								{% if value == 'mafia' %}
									Мафиози
								{% endif %}
							{% endif %}
						{% endfor %}
					</td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>

{% endblock content%}

Site/mafia/user_profile/templates/profile/show_profile.html
{% extends 'profile/profile.html' %}

{% block script %}
{{ super }}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  $('.friendship-button').click(function() {

    $.ajax({
      url: 'add_friendship_record/',
      method: 'POST',
      success: function(response) {
        var block = document.getElementById('EditProfile');
        block.style.display = 'none';
      },
      error: function(xhr, status, error) {
        // Обработка ошибки
        console.log(error);
      }
    });
  });
});

$(document).ready(function() {
  $('.delete_friendship-button').click(function() {

    $.ajax({
      url: 'delete_friendship_record/',
      method: 'POST',
      success: function(response) {
        var block = document.getElementById('EditProfile');
        block.style.display = 'none';
      },
      error: function(xhr, status, error) {
        // Обработка ошибки
        console.log(error);
      }
    });
  });
});

$(document).ready(function() {
  $('.answer_friendship-button').click(function() {
        var dataToSend = {
            record_id: $(this).data('record-id'),
        };
        // Выполните AJAX-запрос
        $.ajax({
            url: '{% url 'add_record'%}',
            method: 'POST',
            data: dataToSend,
            success: function(response) {
                var elementToRemove = document.getElementById("EditProfile");
                if (elementToRemove) {
                    elementToRemove.remove();
                }
            },
            error: function(xhr, status, error) {
                // Обработка ошибки
                console.error('Произошла ошибка при выполнении запроса.');
      }
    });
  });
});
</script>
{% endblock %}